version: "3.1"

services:
  audio_hunter_bot:
    container_name: audio_hunter_bot
    environment:
      BOT_TOKEN: "${BOT_TOKEN:?BOT_TOKEN is required}"
      BOT_ADMIN_USER_ID: "${BOT_ADMIN_USER_ID:?BOT_ADMIN_USER_ID is required}"
      SEARCH_RESULT_COUNT: "${SEARCH_RESULT_COUNT:?SEARCH_RESULT_COUNT is required}"
      DATABASE_PATH: "${DATABASE_PATH:?DATABASE_PATH is required}"
      TOP_USER_REQUESTS_COUNT: "${TOP_USER_REQUESTS_COUNT:?TOP_USER_REQUESTS_COUNT is required}"
      FEEDBACK_MESSAGE: "${FEEDBACK_MESSAGE:?FEEDBACK_MESSAGE is required}"
      WEBAPP_URL: "${WEBAPP_URL:?WEBAPP_URL is required}"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:3000:3000"
